.TH TFETCH 1 "2022 June" "TFetch 0.0.1"

.SH NAME
TFetch \- a fast and minimalistic fetching tool

.SH SYNOPSIS
.SY tfetch

.SY tfetch

.SH DESCRIPTION
.PP
.B tfetch
Is a C written utility to display
system information.

.SH AUTHOR
Originally written by .Thamognya
.IR < https://github.com/Thamognya >

.SH BUGS
Report bugs on github
.IR < https://github.com/Thamognya/TFetch/issues >

.SH SEE ALSO
.BR neofetch (1),

.SH COPYRIGHT
.PP
\fBTFetch\fR is free software:
you can redistribute it and/or modify it under the terms of the
\fIGNU General Public License version 3\fR and \fIMIT Licnese\fR; you adhere to both licenses.
.PP
\fBTFetch\fR is distributed in the hope that it will be useful but WITHOUT ANY WARRANTY;
without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
See the GNU General Public License for more details.
.PP
You should have received a copy of the GNU General Public License along with \fBTFetch\fR.
If not, see
.IR < https://www.gnu.org/licenses/ >.
